# Generated by Selenium IDE
# import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestDefaultSuite():
    def setup_method(self):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_testcase(self):
        self.driver.get("https://www.baidu.com/")
        self.driver.set_window_size(1295, 687)
        self.driver.find_element(By.ID, "kw").click()
        self.driver.find_element(By.ID, "kw").send_keys("哈哈哈哈")
        self.driver.find_element(By.ID, "kw").send_keys(Keys.ENTER)
        element = self.driver.find_element(By.LINK_TEXT, "创作团队")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.LINK_TEXT, "哈哈哈哈哈第二季 - 百度百科").click()
        self.vars["win7587"] = self.wait_for_window(2000)


testDefaultSuite = TestDefaultSuite()
testDefaultSuite.setup_method()
testDefaultSuite.wait_for_window(timeout=2)
testDefaultSuite.test_testcase()
testDefaultSuite.teardown_method()